language: python
dist: xenial
python:
  - "2.7"
  - "3.7"
env:
  - DJANGO_VERSION=1.11.22
  - DJANGO_VERSION=2.2.6
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.2.6
install:
  - pip install -U pip wheel
  - pip install -q Django==$DJANGO_VERSION
  - if [[ $(python -c 'import sys; print(sys.version_info[0])') == 3 ]]; then pip install black; fi
  - python setup.py -q install
script:
  - python manage.py test
  - if [[ $(python -c 'import sys; print(sys.version_info[0])') == 3 ]]; then black . --check; fi
cache: pip
branches:
  only:
  - master
